parameters:
#    eliberty_form.example.class: Eliberty\FormBundle\Example

services:

    eliberty.form.type.boolean:
        class: Eliberty\FormBundle\Form\FormElementType\BooleanType
        tags: [{ name: form.type, alias: eliberty_boolean }]
    eliberty.form.type.markdown.editor:
        class: Eliberty\FormBundle\Form\FormElementType\MarkdownEditorType
        tags: [{ name: form.type, alias: eliberty_markdown_editor }]
    eliberty.form.type.multiselect:
        class: Eliberty\FormBundle\Form\FormElementType\MultiSelectType
        tags: [{ name: form.type, alias: eliberty_multiselect }]
    eliberty.form.type.datepicker:
        class: Eliberty\FormBundle\Form\FormElementType\DatePickerType
        tags: [{ name: form.type, alias: eliberty_datepicker }]
    eliberty.form.type.tags:
        class: Eliberty\FormBundle\Form\FormElementType\TagsType
        tags: [{ name: form.type, alias: eliberty_tags }]
    eliberty.form.type.file.upload:
        class: Eliberty\FormBundle\Form\FormElementType\FileUploadType
        tags: [{ name: form.type, alias: eliberty_file_upload }]
    eliberty.form.type.choice_rest:
        class: Eliberty\FormBundle\Form\FormElementType\RestChoiceType
        tags: [{ name: form.type, alias: eliberty_rest_choice }]
    eliberty.form.type.choice_bnt:
        class: Eliberty\FormBundle\Form\FormElementType\BntChoiceType
        tags: [{ name: form.type, alias: eliberty_bnt_choice }]
    eliberty.form.type.expanded:
        class: Eliberty\FormBundle\Form\FormElementType\ExpandedType
        tags: [{ name: form.type, alias: eliberty_expanded }]
    eliberty.form.type.chosen:
        class: Eliberty\FormBundle\Form\FormElementType\ChosenType
        tags: [{ name: form.type, alias: eliberty_chosen }]
    eliberty.form.type.chosen.entity:
        class: Eliberty\FormBundle\Form\FormElementType\ChosenEntityType
        tags: [{ name: form.type, alias: eliberty_chosen_entity }]
    eliberty.form.type.keycard.skidata:
        class: Eliberty\FormBundle\Form\FormElementType\KeycardSkidataType
        tags: [{ name: form.type, alias: eliberty_keycard_skidata }]
    eliberty.form.type.keycard.teamaxess:
            class: Eliberty\FormBundle\Form\FormElementType\KeycardTeamaxessType
            tags: [{ name: form.type, alias: eliberty_keycard_teamaxess }]

    ##Defined form polymorphe collections
    eliberty.form.polycollection_type:
        class: Eliberty\FormBundle\Form\FormElementType\PolyCollectionType
        tags:
            - { name: form.type, alias: eliberty_polycollection}

    eliberty.form.type.entity_hidden:
         class: Eliberty\FormBundle\Form\FormElementType\EntityHiddenType
         arguments: ["@doctrine.orm.entity_manager"]
         tags:
         - { name: form.type, alias: eliberty_entity_hidden }





